<!DOCTYPE html>
<html>
<head>
    <title>{{ $department->name }} Faculty Compliance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            line-height: 1.3;
            margin: 0;
            padding: 15px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #007bff;
            margin: 0 0 5px 0;
            font-size: 20px;
        }
        .header h2 {
            color: #6c757d;
            margin: 0;
            font-size: 16px;
            font-weight: normal;
        }
        .meta-info {
            background: #f8f9fa;
            padding: 12px;
            margin-bottom: 20px;
            border-radius: 3px;
            font-size: 10px;
        }
        .program-section {
            margin-bottom: 25px;
            page-break-inside: avoid;
        }
        .program-header {
            background: #e9ecef;
            padding: 8px;
            font-weight: bold;
            border-left: 4px solid #007bff;
            margin-bottom: 10px;
        }
        .faculty-section {
            margin-bottom: 20px;
            page-break-inside: avoid;
        }
        .faculty-header {
            background: #f8f9fa;
            padding: 6px 8px;
            font-weight: bold;
            border-left: 3px solid #28a745;
            margin-bottom: 8px;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 8px;
            font-size: 10px;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 4px 6px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background: #f8f9fa;
            font-weight: bold;
            font-size: 9px;
        }
        .section-title {
            font-weight: bold;
            color: #495057;
            margin: 12px 0 6px 0;
            font-size: 11px;
            border-bottom: 1px solid #dee2e6;
            padding-bottom: 2px;
        }
        .text-center { text-align: center; }
        .text-success { color: #28a745; }
        .text-warning { color: #ffc107; }
        .text-danger { color: #dc3545; }
        .text-muted { color: #6c757d; }
        .badge-success { background: #28a745; color: white; padding: 2px 4px; border-radius: 2px; }
        .badge-danger { background: #dc3545; color: white; padding: 2px 4px; border-radius: 2px; }
        .badge-warning { background: #ffc107; color: black; padding: 2px 4px; border-radius: 2px; }
        .badge-secondary { background: #6c757d; color: white; padding: 2px 4px; border-radius: 2px; }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #6c757d;
            border-top: 1px solid #dee2e6;
            padding-top: 10px;
        }
        .no-data {
            text-align: center;
            padding: 15px;
            color: #6c757d;
            font-style: italic;
        }
        .compliance-summary {
            background: #e7f3ff;
            padding: 6px 8px;
            margin-bottom: 8px;
            border-radius: 3px;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $department->name }}</h1>
        <h2>Faculty Compliance Detailed Report</h2>
    </div>

    <div class="meta-info">
        <strong>Report Generated:</strong> {{ $generated_at->format('F j, Y \a\t g:i A') }}<br>
        <strong>Generated By:</strong> {{ $generated_by }}<br>
        <strong>Department:</strong> {{ $department->name }}<br>
        <strong>Current Semester:</strong> {{ $current_semester ? $current_semester->name . ' ' . $current_semester->academic_year : 'No active semester' }}<br>
        <strong>Total Programs:</strong> {{ $programs->count() }}
    </div>

    @foreach($programs as $program)
    <div class="program-section">
        <div class="program-header">
            {{ $program['name'] }} 
            <span style="float: right;">
                {{ $program['total_faculty'] }} Faculty Members | 
                Avg. Compliance: {{ number_format($program['avg_compliance_rate'], 1) }}%
            </span>
        </div>

        @if($program['faculty']->count() > 0)
            @foreach($program['faculty'] as $faculty)
            <div class="faculty-section">
                <div class="faculty-header">
                    {{ $faculty['name'] }} ({{ $faculty['email'] }})
                    <span style="float: right;">
                        Overall Compliance: {{ $faculty['compliance_rate'] }}% 
                        ({{ $faculty['complied_count'] }}/{{ $faculty['total_compliances'] }})
                    </span>
                </div>

                <div class="compliance-summary">
                    <strong>Summary:</strong> 
                    {{ $faculty['complied_count'] }} complied out of {{ $faculty['total_compliances'] }} total requirements
                    @if($faculty['compliance_rate'] >= 80)
                        <span class="badge-success">Excellent</span>
                    @elseif($faculty['compliance_rate'] >= 60)
                        <span class="badge-warning">Good</span>
                    @elseif($faculty['compliance_rate'] >= 40)
                        <span style="background: #fd7e14; color: white; padding: 2px 4px; border-radius: 2px;">Needs Improvement</span>
                    @else
                        <span class="badge-danger">Critical</span>
                    @endif
                </div>

                @if($faculty['semester_compliances']->count() > 0)
                <div class="section-title">Semester-wide Requirements</div>
                <table>
                    <thead>
                        <tr>
                            <th style="width: 25%;">Document Type</th>
                            <th style="width: 15%;">Status</th>
                            <th style="width: 30%;">Evidence Link</th>
                            <th style="width: 15%;">Approval Status</th>
                            <th style="width: 15%;">Compliance</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($faculty['semester_compliances'] as $compliance)
                        <tr>
                            <td>
                                <strong>{{ $compliance->documentType->name }}</strong>
                                @if($compliance->documentType->description)
                                <br><small class="text-muted">{{ Str::limit($compliance->documentType->description, 40) }}</small>
                                @endif
                            </td>
                            <td class="text-center">
                                @if($compliance->self_evaluation_status === 'Complied')
                                    <span class="badge-success">Complied</span>
                                @else
                                    <span class="badge-danger">Not Complied</span>
                                @endif
                            </td>
                            <td>
                                @if($compliance->evidence_link)
                                    <small>{{ Str::limit($compliance->evidence_link, 35) }}</small>
                                @else
                                    <span class="text-muted">No link provided</span>
                                @endif
                            </td>
                            <td class="text-center">
                                @if($compliance->approval_status === 'approved')
                                    <span class="badge-success">Approved</span>
                                @elseif($compliance->approval_status === 'needs_revision')
                                    <span class="badge-warning">Needs Revision</span>
                                @elseif($compliance->approval_status === 'pending')
                                    <span class="badge-warning">Pending</span>
                                @else
                                    <span class="badge-secondary">Not Reviewed</span>
                                @endif
                            </td>
                            <td class="text-center">
                                @if($compliance->self_evaluation_status === 'Complied')
                                    <span class="text-success">✓</span>
                                @else
                                    <span class="text-danger">✗</span>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                @endif

                @if($faculty['assigned_subjects']->count() > 0)
                <div class="section-title">Subject-specific Requirements</div>
                @foreach($faculty['assigned_subjects'] as $subjectData)
                    <div style="margin-bottom: 12px;">
                        <strong style="color: #495057;">{{ $subjectData['subject']->code }} - {{ $subjectData['subject']->name }}</strong>
                        
                        @if($subjectData['compliances']->count() > 0)
                        <table style="margin-top: 4px;">
                            <thead>
                                <tr>
                                    <th style="width: 25%;">Document Type</th>
                                    <th style="width: 15%;">Status</th>
                                    <th style="width: 30%;">Evidence Link</th>
                                    <th style="width: 15%;">Approval Status</th>
                                    <th style="width: 15%;">Compliance</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($subjectData['compliances'] as $compliance)
                                <tr>
                                    <td>
                                        <strong>{{ $compliance->documentType->name }}</strong>
                                        @if($compliance->documentType->description)
                                        <br><small class="text-muted">{{ Str::limit($compliance->documentType->description, 30) }}</small>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($compliance->self_evaluation_status === 'Complied')
                                            <span class="badge-success">Complied</span>
                                        @else
                                            <span class="badge-danger">Not Complied</span>
                                        @endif
                                    </td>
                                    <td>
                                        @if($compliance->evidence_link)
                                            <small>{{ Str::limit($compliance->evidence_link, 30) }}</small>
                                        @else
                                            <span class="text-muted">No link provided</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($compliance->approval_status === 'approved')
                                            <span class="badge-success">Approved</span>
                                        @elseif($compliance->approval_status === 'needs_revision')
                                            <span class="badge-warning">Needs Revision</span>
                                        @elseif($compliance->approval_status === 'pending')
                                            <span class="badge-warning">Pending</span>
                                        @else
                                            <span class="badge-secondary">Not Reviewed</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($compliance->self_evaluation_status === 'Complied')
                                            <span class="text-success">✓</span>
                                        @else
                                            <span class="text-danger">✗</span>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        @else
                        <div class="no-data">No subject-specific requirements found for this subject.</div>
                        @endif
                    </div>
                @endforeach
                @else
                <div class="no-data">No assigned subjects found for this faculty member.</div>
                @endif
            </div>
            @endforeach
        @else
        <div class="no-data">No faculty members assigned to this program.</div>
        @endif
    </div>
    @endforeach

    <div class="footer">
        <p>This detailed compliance report was automatically generated by TracAdemics Academic Compliance System</p>
        <p>Report includes semester-wide and subject-specific requirements for all faculty members</p>
        <p>© {{ date('Y') }} {{ config('app.name', 'TracAdemics') }} - All rights reserved</p>
    </div>
</body>
</html>
