<!DOCTYPE html>
<html>
<head>
    <title>{{ $department->name }} Compliance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #007bff;
            margin: 0;
        }
        .meta-info {
            background: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .program-section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .program-header {
            background: #e9ecef;
            padding: 10px;
            font-weight: bold;
            border-left: 4px solid #007bff;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 8px;
            text-align: left;
        }
        th {
            background: #f8f9fa;
            font-weight: bold;
        }
        .text-center { text-align: center; }
        .text-success { color: #28a745; }
        .text-warning { color: #ffc107; }
        .text-danger { color: #dc3545; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $department->name }}</h1>
        <h2>Faculty Compliance Report</h2>
    </div>

    <div class="meta-info">
        <strong>Report Generated:</strong> {{ $generated_at->format('F j, Y \a\t g:i A') }}<br>
        <strong>Generated By:</strong> {{ $generated_by }}<br>
        <strong>Department:</strong> {{ $department->name }}<br>
        <strong>Total Programs:</strong> {{ $programs->count() }}
    </div>

    @foreach($programs as $program)
    <div class="program-section">
        <div class="program-header">
            {{ $program['name'] }} 
            <span style="float: right;">
                {{ $program['total_faculty'] }} Faculty Members | 
                Avg. Compliance: {{ number_format($program['avg_compliance_rate'], 1) }}%
            </span>
        </div>

        @if($program['faculty']->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Faculty Name</th>
                    <th>Email</th>
                    <th>Total Submissions</th>
                    <th>Approved</th>
                    <th>Compliance Rate</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($program['faculty'] as $faculty)
                <tr>
                    <td>{{ $faculty['name'] }}</td>
                    <td>{{ $faculty['email'] }}</td>
                    <td class="text-center">{{ $faculty['total_submissions'] }}</td>
                    <td class="text-center">{{ $faculty['approved_submissions'] }}</td>
                    <td class="text-center">{{ $faculty['compliance_rate'] }}%</td>
                    <td class="text-center">
                        @if($faculty['compliance_rate'] >= 80)
                            <span class="text-success">Excellent</span>
                        @elseif($faculty['compliance_rate'] >= 60)
                            <span class="text-warning">Good</span>
                        @elseif($faculty['compliance_rate'] >= 40)
                            <span style="color: #fd7e14;">Needs Improvement</span>
                        @else
                            <span class="text-danger">Critical</span>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <p style="text-align: center; padding: 20px; color: #6c757d;">
            No faculty members assigned to this program.
        </p>
        @endif
    </div>
    @endforeach

    <div class="footer">
        <p>This report was automatically generated by TracAdemics Academic Compliance System</p>
        <p>© {{ date('Y') }} Brokenshire University - All rights reserved</p>
    </div>
</body>
</html>
